exchange_pair_map:
  binance:
    - pair: btcusdt
      ws_api: false
  bitstamp:
    - pair: btcusd
server_addr: "127.0.0.1"
server_port: 50051
log_path: "test.log"
# Debug, Info, Warning, Error
log_level: "Debug"
