exchange_pair_map:
  #binance:
  #- btcusdt
  #bitstamp:
  #- btcusd
  independentreserve:
    - pair: Xbt-aud
      ws_api: false
      wait_secs: 1
  btcmarkets:
    - pair: BTC-AUD
    #BTC-USDT is closed
  coinjar:
    - pair: BTCAUD
  kraken:
    - pair: XBT/AUD
bind_addr: "127.0.0.1"
server_addr: "127.0.0.1"
server_port: 50051
log_path: "test.log"
# Debug, Info, Warning, Error
log_level: "Warning"
