name: CI

on:
  workflow_dispatch: # allow manual triggering
    inputs:
      create_release:
        description: "Create new release"
        required: true
        type: boolean
  push:
    branches:
      - main
      - test
    paths: [".github/workflows/**", "**/Cargo.toml", "**/Cargo.lock", "**/*.rs"]
  pull_request:
    types: [opened, synchronize, repoened]
    paths: [".github/workflows/**", "**/Cargo.toml", "**/Cargo.lock", "**/*.rs"]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    container: ubuntu:18.04

    steps:
      - name: Packages
        id: packages
        run: sudo apt update && sudo apt install -y libssl-dev

      - name: Prepare
        id: prepare
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

      - name: Clone
        id: checkout
        uses: actions/checkout@v1

      - name: Dependencies
        id: depends
        run: rustup update nightly && rustup default nightly

      - name: build
        id: build
        run: OPENSSL_STATIC=1 OPENSSL_LIB_DIR=/lib/x86_64-linux-gnu/ OPENSSL_INCLUDE_DIR=/usr/include cargo build --release

      - name: test
        id: test
        run: OPENSSL_STATIC=1 OPENSSL_LIB_DIR=/lib/x86_64-linux-gnu/ OPENSSL_INCLUDE_DIR=/usr/include cargo test --release

      - name: upload
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) }}
        uses: actions/upload-artifact@v3
        with:
          path: |
            target/release/arb_monitor
